// app/layout.tsx
// ai-ignore-file
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Leerwaba App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 no-underline`}> {/* Added no-underline */}
        <main className="container mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  )
}
